[profile.default]
evm_version = 'london'
gas_reports = ['*']
libs = ['lib']
line_length = 80
optimizer = true
optimizer_runs = 10000
out = 'out'
solc = '0.8.16'
src = 'src'
verbosity = 2

[rpc_endpoints]
localhost = "${LOCALHOST}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
etherscan = {key = "${ETHERSCAN_API_KEY}"}

[fuzz]
runs = 1000

[doc]
out = "forge-doc"

[fmt]
line_length = 100

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
